CREATE DATABASE IF NOT EXISTS hotel_management;
USE hotel_management;

-- Tabla CLIENTE
CREATE TABLE IF NOT EXISTS CLIENTE (
    id_cliente INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    correo VARCHAR(100) NOT NULL,
    telefono VARCHAR(20) NOT NULL
);

-- Tabla HABITACION
CREATE TABLE IF NOT EXISTS HABITACION (
    id_habitacion INT AUTO_INCREMENT PRIMARY KEY,
    tipo VARCHAR(50) NOT NULL,
    precio DECIMAL(10, 2) NOT NULL
);

-- Tabla EMPLEADO
CREATE TABLE IF NOT EXISTS EMPLEADO (
    id_empleado INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    puesto VARCHAR(50) NOT NULL
);

-- Tabla RESERVA
CREATE TABLE IF NOT EXISTS RESERVA (
    id_reserva INT AUTO_INCREMENT PRIMARY KEY,
    fecha_entrada DATE NOT NULL,
    fecha_salida DATE NOT NULL,
    CLIENTE_id_cliente INT NOT NULL,
    HABITACION_id_habitacion INT NOT NULL,
    FOREIGN KEY (CLIENTE_id_cliente) REFERENCES CLIENTE(id_cliente) ON DELETE CASCADE,
    FOREIGN KEY (HABITACION_id_habitacion) REFERENCES HABITACION(id_habitacion) ON DELETE CASCADE
);

-- Tabla PAGO
CREATE TABLE IF NOT EXISTS PAGO (
    id_pago INT AUTO_INCREMENT PRIMARY KEY,
    fecha_pago DATE NOT NULL,
    monto DECIMAL(10, 2) NOT NULL,
    metodo_pago VARCHAR(50) NOT NULL,
    RESERVA_id_reserva INT NOT NULL,
    EMPLEADO_id_empleado INT NOT NULL,
    FOREIGN KEY (RESERVA_id_reserva) REFERENCES RESERVA(id_reserva) ON DELETE CASCADE,
    FOREIGN KEY (EMPLEADO_id_empleado) REFERENCES EMPLEADO(id_empleado) ON DELETE CASCADE
);

-- Tabla LOG_HABITACION
CREATE TABLE IF NOT EXISTS LOG_HABITACION (
    id_log INT AUTO_INCREMENT PRIMARY KEY,
    HABITACION_id_habitacion INT NOT NULL,
    status VARCHAR(50) NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (HABITACION_id_habitacion) REFERENCES HABITACION(id_habitacion) ON DELETE CASCADE
);
